package com.osi.finx.model;
// Generated 08 14, 18 5:23:14 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * QxmaFtBank generated by hbm2java
 */
@Entity
@Table(name = "qxma_ft_bank", catalog = "finx_db")
public class QxmaFtBank implements java.io.Serializable {

	private QxmaFtBankId id;
	private QxmaFtBankAcctClass qxmaFtBankAcctClass;
	private QxmaFtBankAcctType qxmaFtBankAcctType;
	private String name;
	private String swiftCode;
	private String phoneNo;
	private Date timeStampTz;

	public QxmaFtBank() {
	}

	public QxmaFtBank(QxmaFtBankId id, QxmaFtBankAcctClass qxmaFtBankAcctClass, QxmaFtBankAcctType qxmaFtBankAcctType) {
		this.id = id;
		this.qxmaFtBankAcctClass = qxmaFtBankAcctClass;
		this.qxmaFtBankAcctType = qxmaFtBankAcctType;
	}

	public QxmaFtBank(QxmaFtBankId id, QxmaFtBankAcctClass qxmaFtBankAcctClass, QxmaFtBankAcctType qxmaFtBankAcctType,
			String name, String swiftCode, String phoneNo, Date timeStampTz) {
		this.id = id;
		this.qxmaFtBankAcctClass = qxmaFtBankAcctClass;
		this.qxmaFtBankAcctType = qxmaFtBankAcctType;
		this.name = name;
		this.swiftCode = swiftCode;
		this.phoneNo = phoneNo;
		this.timeStampTz = timeStampTz;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "bankId", column = @Column(name = "bank_id", nullable = false)),
			@AttributeOverride(name = "bankAccountTypeBaType", column = @Column(name = "bank_account_type_ba_type", nullable = false)),
			@AttributeOverride(name = "bankAccountClassBaId", column = @Column(name = "bank_account_class_ba_id", nullable = false)) })
	public QxmaFtBankId getId() {
		return this.id;
	}

	public void setId(QxmaFtBankId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bank_account_class_ba_id", nullable = false, insertable = false, updatable = false)
	public QxmaFtBankAcctClass getQxmaFtBankAcctClass() {
		return this.qxmaFtBankAcctClass;
	}

	public void setQxmaFtBankAcctClass(QxmaFtBankAcctClass qxmaFtBankAcctClass) {
		this.qxmaFtBankAcctClass = qxmaFtBankAcctClass;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "bank_account_type_ba_type", nullable = false, insertable = false, updatable = false)
	public QxmaFtBankAcctType getQxmaFtBankAcctType() {
		return this.qxmaFtBankAcctType;
	}

	public void setQxmaFtBankAcctType(QxmaFtBankAcctType qxmaFtBankAcctType) {
		this.qxmaFtBankAcctType = qxmaFtBankAcctType;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "swift_code", length = 50)
	public String getSwiftCode() {
		return this.swiftCode;
	}

	public void setSwiftCode(String swiftCode) {
		this.swiftCode = swiftCode;
	}

	@Column(name = "phone_no", length = 12)
	public String getPhoneNo() {
		return this.phoneNo;
	}

	public void setPhoneNo(String phoneNo) {
		this.phoneNo = phoneNo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time_stamp_tz", length = 19)
	public Date getTimeStampTz() {
		return this.timeStampTz;
	}

	public void setTimeStampTz(Date timeStampTz) {
		this.timeStampTz = timeStampTz;
	}

}
