package com.osi.finx.model;
// Generated 08 16, 18 6:39:07 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * QxmaFtChargeStatus generated by hbm2java
 */
@Entity
@Table(name = "qxma_ft_charge_status", catalog = "finx_db")
public class QxmaFtChargeStatus implements java.io.Serializable {

	private Long csId;
	private String code;
	private String description;
	private Set<QxmaFtCharges> qxmaFtChargeses = new HashSet<QxmaFtCharges>(0);

	public QxmaFtChargeStatus() {
	}

	public QxmaFtChargeStatus(String code) {
		this.code = code;
	}

	public QxmaFtChargeStatus(String code, String description, Set<QxmaFtCharges> qxmaFtChargeses) {
		this.code = code;
		this.description = description;
		this.qxmaFtChargeses = qxmaFtChargeses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "cs_id", unique = true, nullable = false)
	public Long getCsId() {
		return this.csId;
	}

	public void setCsId(Long csId) {
		this.csId = csId;
	}

	@Column(name = "code", nullable = false, length = 10)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "description", length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "qxmaFtChargeStatus")
	public Set<QxmaFtCharges> getQxmaFtChargeses() {
		return this.qxmaFtChargeses;
	}

	public void setQxmaFtChargeses(Set<QxmaFtCharges> qxmaFtChargeses) {
		this.qxmaFtChargeses = qxmaFtChargeses;
	}

}
