package com.osi.finx.model;
// Generated 08 16, 18 6:39:07 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * QxmaPlItemId generated by hbm2java
 */
@Embeddable
public class QxmaPlItemId implements java.io.Serializable {

	private long itemId;
	private String payloadId;

	public QxmaPlItemId() {
	}

	public QxmaPlItemId(long itemId, String payloadId) {
		this.itemId = itemId;
		this.payloadId = payloadId;
	}

	@Column(name = "item_id", nullable = false)
	public long getItemId() {
		return this.itemId;
	}

	public void setItemId(long itemId) {
		this.itemId = itemId;
	}

	@Column(name = "payload_id", nullable = false, length = 15)
	public String getPayloadId() {
		return this.payloadId;
	}

	public void setPayloadId(String payloadId) {
		this.payloadId = payloadId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof QxmaPlItemId))
			return false;
		QxmaPlItemId castOther = (QxmaPlItemId) other;

		return (this.getItemId() == castOther.getItemId())
				&& ((this.getPayloadId() == castOther.getPayloadId()) || (this.getPayloadId() != null
						&& castOther.getPayloadId() != null && this.getPayloadId().equals(castOther.getPayloadId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getItemId();
		result = 37 * result + (getPayloadId() == null ? 0 : this.getPayloadId().hashCode());
		return result;
	}

}
