package com.osi.finx.model;
// Generated 08 14, 18 5:23:14 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * QxmaFtLedgerType generated by hbm2java
 */
@Entity
@Table(name = "qxma_ft_ledger_type", catalog = "finx_db")
public class QxmaFtLedgerType implements java.io.Serializable {

	private Long ledgerTypeId;
	private String code;
	private String description;
	private Set<QxmaFtLedger> qxmaFtLedgers = new HashSet<QxmaFtLedger>(0);

	public QxmaFtLedgerType() {
	}

	public QxmaFtLedgerType(String code) {
		this.code = code;
	}

	public QxmaFtLedgerType(String code, String description, Set<QxmaFtLedger> qxmaFtLedgers) {
		this.code = code;
		this.description = description;
		this.qxmaFtLedgers = qxmaFtLedgers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ledger_type_id", unique = true, nullable = false)
	public Long getLedgerTypeId() {
		return this.ledgerTypeId;
	}

	public void setLedgerTypeId(Long ledgerTypeId) {
		this.ledgerTypeId = ledgerTypeId;
	}

	@Column(name = "code", nullable = false, length = 10)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "description", length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "qxmaFtLedgerType")
	public Set<QxmaFtLedger> getQxmaFtLedgers() {
		return this.qxmaFtLedgers;
	}

	public void setQxmaFtLedgers(Set<QxmaFtLedger> qxmaFtLedgers) {
		this.qxmaFtLedgers = qxmaFtLedgers;
	}

}
