package com.osi.finx.model;
// Generated 08 14, 18 5:23:14 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * QxmaFtLedgerStatus generated by hbm2java
 */
@Entity
@Table(name = "qxma_ft_ledger_status", catalog = "finx_db")
public class QxmaFtLedgerStatus implements java.io.Serializable {

	private Long ledgerStatusId;
	private String code;
	private String description;
	private Set<QxmaFtLedger> qxmaFtLedgers = new HashSet<QxmaFtLedger>(0);

	public QxmaFtLedgerStatus() {
	}

	public QxmaFtLedgerStatus(String code) {
		this.code = code;
	}

	public QxmaFtLedgerStatus(String code, String description, Set<QxmaFtLedger> qxmaFtLedgers) {
		this.code = code;
		this.description = description;
		this.qxmaFtLedgers = qxmaFtLedgers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ledger_status_id", unique = true, nullable = false)
	public Long getLedgerStatusId() {
		return this.ledgerStatusId;
	}

	public void setLedgerStatusId(Long ledgerStatusId) {
		this.ledgerStatusId = ledgerStatusId;
	}

	@Column(name = "code", nullable = false, length = 10)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "description", length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "qxmaFtLedgerStatus")
	public Set<QxmaFtLedger> getQxmaFtLedgers() {
		return this.qxmaFtLedgers;
	}

	public void setQxmaFtLedgers(Set<QxmaFtLedger> qxmaFtLedgers) {
		this.qxmaFtLedgers = qxmaFtLedgers;
	}

}
