package com.osi.finx.model;
// Generated 09 7, 18 3:23:59 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * QxmaLegalEntity generated by hbm2java
 */
@Entity
@Table(name = "qxma_legal_entity", catalog = "finx_db", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class QxmaLegalEntity implements java.io.Serializable {

	private String code;
	private QxmaOrganization qxmaOrganization;
	private String name;

	public QxmaLegalEntity() {
	}

	public QxmaLegalEntity(String code, QxmaOrganization qxmaOrganization, String name) {
		this.code = code;
		this.qxmaOrganization = qxmaOrganization;
		this.name = name;
	}

	@Id

	@Column(name = "code", unique = true, nullable = false, length = 30)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "org_code", nullable = false)
	public QxmaOrganization getQxmaOrganization() {
		return this.qxmaOrganization;
	}

	public void setQxmaOrganization(QxmaOrganization qxmaOrganization) {
		this.qxmaOrganization = qxmaOrganization;
	}

	@Column(name = "name", unique = true, nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
