package com.osi.finx.model;
// Generated 09 7, 18 3:23:59 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * QxmaAppShare generated by hbm2java
 */
@Entity
@Table(name = "qxma_app_share", catalog = "finx_db")
public class QxmaAppShare implements java.io.Serializable {

	private Integer id;
	private String appName;
	private Set<QxmaAppOmsShare> qxmaAppOmsShares = new HashSet<QxmaAppOmsShare>(0);
	private Set<QxmaAppFtShare> qxmaAppFtShares = new HashSet<QxmaAppFtShare>(0);

	public QxmaAppShare() {
	}

	public QxmaAppShare(String appName) {
		this.appName = appName;
	}

	public QxmaAppShare(String appName, Set<QxmaAppOmsShare> qxmaAppOmsShares, Set<QxmaAppFtShare> qxmaAppFtShares) {
		this.appName = appName;
		this.qxmaAppOmsShares = qxmaAppOmsShares;
		this.qxmaAppFtShares = qxmaAppFtShares;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "app_name", nullable = false, length = 100)
	public String getAppName() {
		return this.appName;
	}

	public void setAppName(String appName) {
		this.appName = appName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "qxmaAppShare")
	public Set<QxmaAppOmsShare> getQxmaAppOmsShares() {
		return this.qxmaAppOmsShares;
	}

	public void setQxmaAppOmsShares(Set<QxmaAppOmsShare> qxmaAppOmsShares) {
		this.qxmaAppOmsShares = qxmaAppOmsShares;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "qxmaAppShare")
	public Set<QxmaAppFtShare> getQxmaAppFtShares() {
		return this.qxmaAppFtShares;
	}

	public void setQxmaAppFtShares(Set<QxmaAppFtShare> qxmaAppFtShares) {
		this.qxmaAppFtShares = qxmaAppFtShares;
	}

}
