package com.osi.finx.model;
// Generated 09 7, 18 3:23:59 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * QxmaFtProductEvent generated by hbm2java
 */
@Entity
@Table(name = "qxma_ft_product_event", catalog = "finx_db")
public class QxmaFtProductEvent implements java.io.Serializable {

	private Integer ftEventProdId;
	private QxmaFtEventStatus qxmaFtEventStatus;
	private QxmaProductLineType qxmaProductLineType;
	private Set<QxmaAppFtShare> qxmaAppFtShares = new HashSet<QxmaAppFtShare>(0);

	public QxmaFtProductEvent() {
	}

	public QxmaFtProductEvent(QxmaFtEventStatus qxmaFtEventStatus, QxmaProductLineType qxmaProductLineType) {
		this.qxmaFtEventStatus = qxmaFtEventStatus;
		this.qxmaProductLineType = qxmaProductLineType;
	}

	public QxmaFtProductEvent(QxmaFtEventStatus qxmaFtEventStatus, QxmaProductLineType qxmaProductLineType,
			Set<QxmaAppFtShare> qxmaAppFtShares) {
		this.qxmaFtEventStatus = qxmaFtEventStatus;
		this.qxmaProductLineType = qxmaProductLineType;
		this.qxmaAppFtShares = qxmaAppFtShares;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ft_event_prod_id", unique = true, nullable = false)
	public Integer getFtEventProdId() {
		return this.ftEventProdId;
	}

	public void setFtEventProdId(Integer ftEventProdId) {
		this.ftEventProdId = ftEventProdId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ft_event_code", nullable = false)
	public QxmaFtEventStatus getQxmaFtEventStatus() {
		return this.qxmaFtEventStatus;
	}

	public void setQxmaFtEventStatus(QxmaFtEventStatus qxmaFtEventStatus) {
		this.qxmaFtEventStatus = qxmaFtEventStatus;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "prod_line_type_id", nullable = false)
	public QxmaProductLineType getQxmaProductLineType() {
		return this.qxmaProductLineType;
	}

	public void setQxmaProductLineType(QxmaProductLineType qxmaProductLineType) {
		this.qxmaProductLineType = qxmaProductLineType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "qxmaFtProductEvent")
	public Set<QxmaAppFtShare> getQxmaAppFtShares() {
		return this.qxmaAppFtShares;
	}

	public void setQxmaAppFtShares(Set<QxmaAppFtShare> qxmaAppFtShares) {
		this.qxmaAppFtShares = qxmaAppFtShares;
	}

}
