package com.osi.finx.model;
// Generated 08 14, 18 5:23:14 PM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * QxmaPlItem generated by hbm2java
 */
@Entity
@Table(name = "qxma_pl_item", catalog = "finx_db")
public class QxmaPlItem implements java.io.Serializable {

	private QxmaPlItemId id;
	private QxmaPayload qxmaPayload;
	private String type;
	private String description;
	private Double amount;
	private Integer quantity;
	private BigDecimal total;
	private Character metadata;
	private BigDecimal insuredValue;

	public QxmaPlItem() {
	}

	public QxmaPlItem(QxmaPlItemId id, QxmaPayload qxmaPayload) {
		this.id = id;
		this.qxmaPayload = qxmaPayload;
	}

	public QxmaPlItem(QxmaPlItemId id, QxmaPayload qxmaPayload, String type, String description, Double amount,
			Integer quantity, BigDecimal total, Character metadata, BigDecimal insuredValue) {
		this.id = id;
		this.qxmaPayload = qxmaPayload;
		this.type = type;
		this.description = description;
		this.amount = amount;
		this.quantity = quantity;
		this.total = total;
		this.metadata = metadata;
		this.insuredValue = insuredValue;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "itemId", column = @Column(name = "item_id", nullable = false)),
			@AttributeOverride(name = "payloadId", column = @Column(name = "payload_id", nullable = false, length = 15)) })
	public QxmaPlItemId getId() {
		return this.id;
	}

	public void setId(QxmaPlItemId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "payload_id", nullable = false, insertable = false, updatable = false)
	public QxmaPayload getQxmaPayload() {
		return this.qxmaPayload;
	}

	public void setQxmaPayload(QxmaPayload qxmaPayload) {
		this.qxmaPayload = qxmaPayload;
	}

	@Column(name = "type", length = 10)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "description", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "amount", precision = 22, scale = 0)
	public Double getAmount() {
		return this.amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

	@Column(name = "quantity")
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@Column(name = "total")
	public BigDecimal getTotal() {
		return this.total;
	}

	public void setTotal(BigDecimal total) {
		this.total = total;
	}

	@Column(name = "metadata", length = 0)
	public Character getMetadata() {
		return this.metadata;
	}

	public void setMetadata(Character metadata) {
		this.metadata = metadata;
	}

	@Column(name = "insured_value")
	public BigDecimal getInsuredValue() {
		return this.insuredValue;
	}

	public void setInsuredValue(BigDecimal insuredValue) {
		this.insuredValue = insuredValue;
	}

}
