package com.osi.finx.model;
// Generated 09 7, 18 3:23:59 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * QxmaLineType generated by hbm2java
 */
@Entity
@Table(name = "qxma_line_type", catalog = "finx_db")
public class QxmaLineType implements java.io.Serializable {

	private String code;
	private QxmaAccount qxmaAccount;
	private String name;
	private String activity;
	private String hubs;
	private String inter;
	private String future;
	private String location;
	private Set<QxmaProductLineType> qxmaProductLineTypes = new HashSet<QxmaProductLineType>(0);

	public QxmaLineType() {
	}

	public QxmaLineType(String code, QxmaAccount qxmaAccount, String name) {
		this.code = code;
		this.qxmaAccount = qxmaAccount;
		this.name = name;
	}

	public QxmaLineType(String code, QxmaAccount qxmaAccount, String name, String activity, String hubs, String inter,
			String future, String location, Set<QxmaProductLineType> qxmaProductLineTypes) {
		this.code = code;
		this.qxmaAccount = qxmaAccount;
		this.name = name;
		this.activity = activity;
		this.hubs = hubs;
		this.inter = inter;
		this.future = future;
		this.location = location;
		this.qxmaProductLineTypes = qxmaProductLineTypes;
	}

	@Id

	@Column(name = "code", unique = true, nullable = false, length = 30)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_code", nullable = false)
	public QxmaAccount getQxmaAccount() {
		return this.qxmaAccount;
	}

	public void setQxmaAccount(QxmaAccount qxmaAccount) {
		this.qxmaAccount = qxmaAccount;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "activity", length = 30)
	public String getActivity() {
		return this.activity;
	}

	public void setActivity(String activity) {
		this.activity = activity;
	}

	@Column(name = "hubs", length = 30)
	public String getHubs() {
		return this.hubs;
	}

	public void setHubs(String hubs) {
		this.hubs = hubs;
	}

	@Column(name = "inter", length = 30)
	public String getInter() {
		return this.inter;
	}

	public void setInter(String inter) {
		this.inter = inter;
	}

	@Column(name = "future", length = 30)
	public String getFuture() {
		return this.future;
	}

	public void setFuture(String future) {
		this.future = future;
	}

	@Column(name = "location", length = 30)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "qxmaLineType")
	public Set<QxmaProductLineType> getQxmaProductLineTypes() {
		return this.qxmaProductLineTypes;
	}

	public void setQxmaProductLineTypes(Set<QxmaProductLineType> qxmaProductLineTypes) {
		this.qxmaProductLineTypes = qxmaProductLineTypes;
	}

}
