package com.osi.finx.model;
// Generated 09 7, 18 3:23:59 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * QxmaOrganization generated by hbm2java
 */
@Entity
@Table(name = "qxma_organization", catalog = "finx_db")
public class QxmaOrganization implements java.io.Serializable {

	private String orgCode;
	private String name;
	private Set<QxmaLegalEntity> qxmaLegalEntities = new HashSet<QxmaLegalEntity>(0);

	public QxmaOrganization() {
	}

	public QxmaOrganization(String orgCode) {
		this.orgCode = orgCode;
	}

	public QxmaOrganization(String orgCode, String name, Set<QxmaLegalEntity> qxmaLegalEntities) {
		this.orgCode = orgCode;
		this.name = name;
		this.qxmaLegalEntities = qxmaLegalEntities;
	}

	@Id

	@Column(name = "org_code", unique = true, nullable = false, length = 30)
	public String getOrgCode() {
		return this.orgCode;
	}

	public void setOrgCode(String orgCode) {
		this.orgCode = orgCode;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "qxmaOrganization")
	public Set<QxmaLegalEntity> getQxmaLegalEntities() {
		return this.qxmaLegalEntities;
	}

	public void setQxmaLegalEntities(Set<QxmaLegalEntity> qxmaLegalEntities) {
		this.qxmaLegalEntities = qxmaLegalEntities;
	}

}
