package com.osi.finx.model;
// Generated 08 16, 18 6:39:07 PM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * QxmaFtCharges generated by hbm2java
 */
@Entity
@Table(name = "qxma_ft_charges", catalog = "finx_db")
public class QxmaFtCharges implements java.io.Serializable {

	private long orderId;
	private QxmaFtChargeStatus qxmaFtChargeStatus;
	private QxmaFtMatchStatus qxmaFtMatchStatus;
	private QxmaFtParties qxmaFtParties;
	private String referenceId;
	private Long depositId;
	private BigDecimal totalAmount;
	private BigDecimal tenderedAmount;
	private BigDecimal changeAmount;
	private String remarks;
	private Date createdAt;
	private Long updatedBy;
	private Date updatedAt;

	public QxmaFtCharges() {
	}

	public QxmaFtCharges(long orderId, QxmaFtChargeStatus qxmaFtChargeStatus) {
		this.orderId = orderId;
		this.qxmaFtChargeStatus = qxmaFtChargeStatus;
	}

	public QxmaFtCharges(long orderId, QxmaFtChargeStatus qxmaFtChargeStatus, QxmaFtMatchStatus qxmaFtMatchStatus,
			QxmaFtParties qxmaFtParties, String referenceId, Long depositId, BigDecimal totalAmount,
			BigDecimal tenderedAmount, BigDecimal changeAmount, String remarks, Date createdAt, Long updatedBy,
			Date updatedAt) {
		this.orderId = orderId;
		this.qxmaFtChargeStatus = qxmaFtChargeStatus;
		this.qxmaFtMatchStatus = qxmaFtMatchStatus;
		this.qxmaFtParties = qxmaFtParties;
		this.referenceId = referenceId;
		this.depositId = depositId;
		this.totalAmount = totalAmount;
		this.tenderedAmount = tenderedAmount;
		this.changeAmount = changeAmount;
		this.remarks = remarks;
		this.createdAt = createdAt;
		this.updatedBy = updatedBy;
		this.updatedAt = updatedAt;
	}

	@Id
	@Column(name = "order_id", unique = true, nullable = false)
	public long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(long orderId) {
		this.orderId = orderId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "charge_status_id", nullable = false)
	public QxmaFtChargeStatus getQxmaFtChargeStatus() {
		return this.qxmaFtChargeStatus;
	}

	public void setQxmaFtChargeStatus(QxmaFtChargeStatus qxmaFtChargeStatus) {
		this.qxmaFtChargeStatus = qxmaFtChargeStatus;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "match_status_id")
	public QxmaFtMatchStatus getQxmaFtMatchStatus() {
		return this.qxmaFtMatchStatus;
	}

	public void setQxmaFtMatchStatus(QxmaFtMatchStatus qxmaFtMatchStatus) {
		this.qxmaFtMatchStatus = qxmaFtMatchStatus;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "party_id")
	public QxmaFtParties getQxmaFtParties() {
		return this.qxmaFtParties;
	}

	public void setQxmaFtParties(QxmaFtParties qxmaFtParties) {
		this.qxmaFtParties = qxmaFtParties;
	}

	@Column(name = "reference_id")
	public String getReferenceId() {
		return this.referenceId;
	}

	public void setReferenceId(String referenceId) {
		this.referenceId = referenceId;
	}

	@Column(name = "deposit_id")
	public Long getDepositId() {
		return this.depositId;
	}

	public void setDepositId(Long depositId) {
		this.depositId = depositId;
	}

	@Column(name = "total_amount")
	public BigDecimal getTotalAmount() {
		return this.totalAmount;
	}

	public void setTotalAmount(BigDecimal totalAmount) {
		this.totalAmount = totalAmount;
	}

	@Column(name = "tendered_amount")
	public BigDecimal getTenderedAmount() {
		return this.tenderedAmount;
	}

	public void setTenderedAmount(BigDecimal tenderedAmount) {
		this.tenderedAmount = tenderedAmount;
	}

	@Column(name = "change_amount")
	public BigDecimal getChangeAmount() {
		return this.changeAmount;
	}

	public void setChangeAmount(BigDecimal changeAmount) {
		this.changeAmount = changeAmount;
	}

	@Column(name = "remarks")
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "updated_by")
	public Long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Long updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
