package com.osi.finx.model;
// Generated 08 16, 18 6:39:07 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * QxmaFtCurrencies generated by hbm2java
 */
@Entity
@Table(name = "qxma_ft_currencies", catalog = "finx_db")
public class QxmaFtCurrencies implements java.io.Serializable {

	private Long currencyId;
	private String name;
	private String code;
	private String symbol;
	private Date createdAt;
	private Set<QxmaFtLedger> qxmaFtLedgers = new HashSet<QxmaFtLedger>(0);
	private Set<QxmaFtWallet> qxmaFtWallets = new HashSet<QxmaFtWallet>(0);

	public QxmaFtCurrencies() {
	}

	public QxmaFtCurrencies(String name, String code) {
		this.name = name;
		this.code = code;
	}

	public QxmaFtCurrencies(String name, String code, String symbol, Date createdAt, Set<QxmaFtLedger> qxmaFtLedgers,
			Set<QxmaFtWallet> qxmaFtWallets) {
		this.name = name;
		this.code = code;
		this.symbol = symbol;
		this.createdAt = createdAt;
		this.qxmaFtLedgers = qxmaFtLedgers;
		this.qxmaFtWallets = qxmaFtWallets;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "currency_id", unique = true, nullable = false)
	public Long getCurrencyId() {
		return this.currencyId;
	}

	public void setCurrencyId(Long currencyId) {
		this.currencyId = currencyId;
	}

	@Column(name = "name", nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "code", nullable = false, length = 5)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "symbol", length = 3)
	public String getSymbol() {
		return this.symbol;
	}

	public void setSymbol(String symbol) {
		this.symbol = symbol;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "qxmaFtCurrencies")
	public Set<QxmaFtLedger> getQxmaFtLedgers() {
		return this.qxmaFtLedgers;
	}

	public void setQxmaFtLedgers(Set<QxmaFtLedger> qxmaFtLedgers) {
		this.qxmaFtLedgers = qxmaFtLedgers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "qxmaFtCurrencies")
	public Set<QxmaFtWallet> getQxmaFtWallets() {
		return this.qxmaFtWallets;
	}

	public void setQxmaFtWallets(Set<QxmaFtWallet> qxmaFtWallets) {
		this.qxmaFtWallets = qxmaFtWallets;
	}

}
