package com.osi.finx.model;
// Generated 09 7, 18 3:23:59 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * QxmaAccountType generated by hbm2java
 */
@Entity
@Table(name = "qxma_account_type", catalog = "finx_db", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class QxmaAccountType implements java.io.Serializable {

	private String code;
	private String name;

	public QxmaAccountType() {
	}

	public QxmaAccountType(String code, String name) {
		this.code = code;
		this.name = name;
	}

	@Id

	@Column(name = "code", unique = true, nullable = false, length = 30)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "name", unique = true, nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
