package com.osi.finx.model;
// Generated 08 16, 18 6:39:07 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * QxmaAddressType generated by hbm2java
 */
@Entity
@Table(name = "qxma_address_type", catalog = "finx_db")
public class QxmaAddressType implements java.io.Serializable {

	private Integer adrTypeId;
	private String name;
	private Set<QxmaPlAddress> qxmaPlAddresses = new HashSet<QxmaPlAddress>(0);

	public QxmaAddressType() {
	}

	public QxmaAddressType(String name) {
		this.name = name;
	}

	public QxmaAddressType(String name, Set<QxmaPlAddress> qxmaPlAddresses) {
		this.name = name;
		this.qxmaPlAddresses = qxmaPlAddresses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "adr_type_id", unique = true, nullable = false)
	public Integer getAdrTypeId() {
		return this.adrTypeId;
	}

	public void setAdrTypeId(Integer adrTypeId) {
		this.adrTypeId = adrTypeId;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "qxmaAddressType")
	public Set<QxmaPlAddress> getQxmaPlAddresses() {
		return this.qxmaPlAddresses;
	}

	public void setQxmaPlAddresses(Set<QxmaPlAddress> qxmaPlAddresses) {
		this.qxmaPlAddresses = qxmaPlAddresses;
	}

}
