package com.osi.finx.model;
// Generated 08 14, 18 5:23:14 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * QxmaFtChargeStatus generated by hbm2java
 */
@Entity
@Table(name = "qxma_ft_charge_status", catalog = "finx_db")
public class QxmaFtChargeStatus implements java.io.Serializable {

	private Long csId;
	private String code;
	private String description;

	public QxmaFtChargeStatus() {
	}

	public QxmaFtChargeStatus(String code) {
		this.code = code;
	}

	public QxmaFtChargeStatus(String code, String description) {
		this.code = code;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "cs_id", unique = true, nullable = false)
	public Long getCsId() {
		return this.csId;
	}

	public void setCsId(Long csId) {
		this.csId = csId;
	}

	@Column(name = "code", nullable = false, length = 10)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "description", length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
