package com.osi.finx.model;
// Generated 08 16, 18 6:39:07 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * QxmaPlConsignee generated by hbm2java
 */
@Entity
@Table(name = "qxma_pl_consignee", catalog = "finx_db")
public class QxmaPlConsignee implements java.io.Serializable {

	private QxmaPlConsigneeId id;
	private QxmaPayload qxmaPayload;
	private String firstname;
	private String lastname;
	private String email;
	private String contactNumber;

	public QxmaPlConsignee() {
	}

	public QxmaPlConsignee(QxmaPlConsigneeId id, QxmaPayload qxmaPayload, String firstname, String lastname) {
		this.id = id;
		this.qxmaPayload = qxmaPayload;
		this.firstname = firstname;
		this.lastname = lastname;
	}

	public QxmaPlConsignee(QxmaPlConsigneeId id, QxmaPayload qxmaPayload, String firstname, String lastname,
			String email, String contactNumber) {
		this.id = id;
		this.qxmaPayload = qxmaPayload;
		this.firstname = firstname;
		this.lastname = lastname;
		this.email = email;
		this.contactNumber = contactNumber;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "consigneeId", column = @Column(name = "consignee_id", nullable = false)),
			@AttributeOverride(name = "payloadId", column = @Column(name = "payload_id", nullable = false, length = 15)) })
	public QxmaPlConsigneeId getId() {
		return this.id;
	}

	public void setId(QxmaPlConsigneeId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "payload_id", nullable = false, insertable = false, updatable = false)
	public QxmaPayload getQxmaPayload() {
		return this.qxmaPayload;
	}

	public void setQxmaPayload(QxmaPayload qxmaPayload) {
		this.qxmaPayload = qxmaPayload;
	}

	@Column(name = "firstname", nullable = false, length = 50)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "lastname", nullable = false, length = 50)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "contact_number", length = 45)
	public String getContactNumber() {
		return this.contactNumber;
	}

	public void setContactNumber(String contactNumber) {
		this.contactNumber = contactNumber;
	}

}
