package com.osi.finx.model;
// Generated 09 7, 18 3:23:59 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * QxmaOmsProductEvent generated by hbm2java
 */
@Entity
@Table(name = "qxma_oms_product_event", catalog = "finx_db")
public class QxmaOmsProductEvent implements java.io.Serializable {

	private Integer omsEventProdId;
	private QxmaOmsEventStatus qxmaOmsEventStatus;
	private QxmaProductLineType qxmaProductLineType;
	private Set<QxmaAppOmsShare> qxmaAppOmsShares = new HashSet<QxmaAppOmsShare>(0);

	public QxmaOmsProductEvent() {
	}

	public QxmaOmsProductEvent(QxmaOmsEventStatus qxmaOmsEventStatus, QxmaProductLineType qxmaProductLineType) {
		this.qxmaOmsEventStatus = qxmaOmsEventStatus;
		this.qxmaProductLineType = qxmaProductLineType;
	}

	public QxmaOmsProductEvent(QxmaOmsEventStatus qxmaOmsEventStatus, QxmaProductLineType qxmaProductLineType,
			Set<QxmaAppOmsShare> qxmaAppOmsShares) {
		this.qxmaOmsEventStatus = qxmaOmsEventStatus;
		this.qxmaProductLineType = qxmaProductLineType;
		this.qxmaAppOmsShares = qxmaAppOmsShares;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "oms_event_prod_id", unique = true, nullable = false)
	public Integer getOmsEventProdId() {
		return this.omsEventProdId;
	}

	public void setOmsEventProdId(Integer omsEventProdId) {
		this.omsEventProdId = omsEventProdId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "oms_event_code", nullable = false)
	public QxmaOmsEventStatus getQxmaOmsEventStatus() {
		return this.qxmaOmsEventStatus;
	}

	public void setQxmaOmsEventStatus(QxmaOmsEventStatus qxmaOmsEventStatus) {
		this.qxmaOmsEventStatus = qxmaOmsEventStatus;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "prod_line_type_id", nullable = false)
	public QxmaProductLineType getQxmaProductLineType() {
		return this.qxmaProductLineType;
	}

	public void setQxmaProductLineType(QxmaProductLineType qxmaProductLineType) {
		this.qxmaProductLineType = qxmaProductLineType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "qxmaOmsProductEvent")
	public Set<QxmaAppOmsShare> getQxmaAppOmsShares() {
		return this.qxmaAppOmsShares;
	}

	public void setQxmaAppOmsShares(Set<QxmaAppOmsShare> qxmaAppOmsShares) {
		this.qxmaAppOmsShares = qxmaAppOmsShares;
	}

}
