package com.osi.finx.model;
// Generated 09 7, 18 3:23:59 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * QxmaAppOmsShare generated by hbm2java
 */
@Entity
@Table(name = "qxma_app_oms_share", catalog = "finx_db")
public class QxmaAppOmsShare implements java.io.Serializable {

	private Integer appOmsId;
	private QxmaAppShare qxmaAppShare;
	private QxmaOmsProductEvent qxmaOmsProductEvent;

	public QxmaAppOmsShare() {
	}

	public QxmaAppOmsShare(QxmaAppShare qxmaAppShare, QxmaOmsProductEvent qxmaOmsProductEvent) {
		this.qxmaAppShare = qxmaAppShare;
		this.qxmaOmsProductEvent = qxmaOmsProductEvent;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "app_oms_id", unique = true, nullable = false)
	public Integer getAppOmsId() {
		return this.appOmsId;
	}

	public void setAppOmsId(Integer appOmsId) {
		this.appOmsId = appOmsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "app_share_id", nullable = false)
	public QxmaAppShare getQxmaAppShare() {
		return this.qxmaAppShare;
	}

	public void setQxmaAppShare(QxmaAppShare qxmaAppShare) {
		this.qxmaAppShare = qxmaAppShare;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "oms_event_prod_id", nullable = false)
	public QxmaOmsProductEvent getQxmaOmsProductEvent() {
		return this.qxmaOmsProductEvent;
	}

	public void setQxmaOmsProductEvent(QxmaOmsProductEvent qxmaOmsProductEvent) {
		this.qxmaOmsProductEvent = qxmaOmsProductEvent;
	}

}
