package com.osi.finx.model;
// Generated 08 14, 18 5:23:14 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * QxmaPlBreakdownId generated by hbm2java
 */
@Embeddable
public class QxmaPlBreakdownId implements java.io.Serializable {

	private long bdId;
	private String payloadId;

	public QxmaPlBreakdownId() {
	}

	public QxmaPlBreakdownId(long bdId, String payloadId) {
		this.bdId = bdId;
		this.payloadId = payloadId;
	}

	@Column(name = "bd_id", nullable = false)
	public long getBdId() {
		return this.bdId;
	}

	public void setBdId(long bdId) {
		this.bdId = bdId;
	}

	@Column(name = "payload_id", nullable = false, length = 15)
	public String getPayloadId() {
		return this.payloadId;
	}

	public void setPayloadId(String payloadId) {
		this.payloadId = payloadId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof QxmaPlBreakdownId))
			return false;
		QxmaPlBreakdownId castOther = (QxmaPlBreakdownId) other;

		return (this.getBdId() == castOther.getBdId())
				&& ((this.getPayloadId() == castOther.getPayloadId()) || (this.getPayloadId() != null
						&& castOther.getPayloadId() != null && this.getPayloadId().equals(castOther.getPayloadId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getBdId();
		result = 37 * result + (getPayloadId() == null ? 0 : this.getPayloadId().hashCode());
		return result;
	}

}
