package com.osi.finx.model;
// Generated 08 14, 18 5:23:14 PM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * QxmaFtWalletLog generated by hbm2java
 */
@Entity
@Table(name = "qxma_ft_wallet_log", catalog = "finx_db")
public class QxmaFtWalletLog implements java.io.Serializable {

	private Long logId;
	private QxmaFtTransfer qxmaFtTransfer;
	private QxmaFtWallet qxmaFtWallet;
	private BigDecimal amount;
	private BigDecimal runningBalance;

	public QxmaFtWalletLog() {
	}

	public QxmaFtWalletLog(QxmaFtTransfer qxmaFtTransfer, QxmaFtWallet qxmaFtWallet) {
		this.qxmaFtTransfer = qxmaFtTransfer;
		this.qxmaFtWallet = qxmaFtWallet;
	}

	public QxmaFtWalletLog(QxmaFtTransfer qxmaFtTransfer, QxmaFtWallet qxmaFtWallet, BigDecimal amount,
			BigDecimal runningBalance) {
		this.qxmaFtTransfer = qxmaFtTransfer;
		this.qxmaFtWallet = qxmaFtWallet;
		this.amount = amount;
		this.runningBalance = runningBalance;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "log_id", unique = true, nullable = false)
	public Long getLogId() {
		return this.logId;
	}

	public void setLogId(Long logId) {
		this.logId = logId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "transfer_id", nullable = false)
	public QxmaFtTransfer getQxmaFtTransfer() {
		return this.qxmaFtTransfer;
	}

	public void setQxmaFtTransfer(QxmaFtTransfer qxmaFtTransfer) {
		this.qxmaFtTransfer = qxmaFtTransfer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "wallet_id", nullable = false)
	public QxmaFtWallet getQxmaFtWallet() {
		return this.qxmaFtWallet;
	}

	public void setQxmaFtWallet(QxmaFtWallet qxmaFtWallet) {
		this.qxmaFtWallet = qxmaFtWallet;
	}

	@Column(name = "amount")
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "running_balance")
	public BigDecimal getRunningBalance() {
		return this.runningBalance;
	}

	public void setRunningBalance(BigDecimal runningBalance) {
		this.runningBalance = runningBalance;
	}

}
