package com.osi.finx.model;
// Generated 09 7, 18 3:23:59 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * QxmaFtPaymentMethod generated by hbm2java
 */
@Entity
@Table(name = "qxma_ft_payment_method", catalog = "finx_db")
public class QxmaFtPaymentMethod implements java.io.Serializable {

	private int pmId;
	private String methodName;
	//private Set<QxmaFtCharges> qxmaFtChargeses = new HashSet<QxmaFtCharges>(0);

	public QxmaFtPaymentMethod() {
	}

	public QxmaFtPaymentMethod(int pmId, String methodName) {
		this.pmId = pmId;
		this.methodName = methodName;
	}

	/*public QxmaFtPaymentMethod(int pmId, String methodName, Set<QxmaFtCharges> qxmaFtChargeses) {
		this.pmId = pmId;
		this.methodName = methodName;
		this.qxmaFtChargeses = qxmaFtChargeses;
	}*/

	@Id

	@Column(name = "pm_id", unique = true, nullable = false)
	public int getPmId() {
		return this.pmId;
	}

	public void setPmId(int pmId) {
		this.pmId = pmId;
	}

	@Column(name = "method_name", nullable = false, length = 50)
	public String getMethodName() {
		return this.methodName;
	}

	public void setMethodName(String methodName) {
		this.methodName = methodName;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "qxmaFtPaymentMethod")
	public Set<QxmaFtCharges> getQxmaFtChargeses() {
		return this.qxmaFtChargeses;
	}

	public void setQxmaFtChargeses(Set<QxmaFtCharges> qxmaFtChargeses) {
		this.qxmaFtChargeses = qxmaFtChargeses;
	}*/

}
