package com.osi.finx.model;
// Generated 08 14, 18 5:23:14 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * QxmaPlAddress generated by hbm2java
 */
@Entity
@Table(name = "qxma_pl_address", catalog = "finx_db")
public class QxmaPlAddress implements java.io.Serializable {

	private QxmaPlAddressId id;
	private QxmaAddressType qxmaAddressType;
	private QxmaPayload qxmaPayload;
	private String type;
	private String firstname;
	private String lastname;
	private String email;
	private String phoneNumber;
	private String mobileNumber;
	private String line1;
	private String line2;
	private String district;
	private String city;
	private String state;
	private String postalCode;
	private String region;
	private String latitude;
	private String longtitude;
	private String country;

	public QxmaPlAddress() {
	}

	public QxmaPlAddress(QxmaPlAddressId id, QxmaAddressType qxmaAddressType, QxmaPayload qxmaPayload) {
		this.id = id;
		this.qxmaAddressType = qxmaAddressType;
		this.qxmaPayload = qxmaPayload;
	}

	public QxmaPlAddress(QxmaPlAddressId id, QxmaAddressType qxmaAddressType, QxmaPayload qxmaPayload, String type,
			String firstname, String lastname, String email, String phoneNumber, String mobileNumber, String line1,
			String line2, String district, String city, String state, String postalCode, String region, String latitude,
			String longtitude, String country) {
		this.id = id;
		this.qxmaAddressType = qxmaAddressType;
		this.qxmaPayload = qxmaPayload;
		this.type = type;
		this.firstname = firstname;
		this.lastname = lastname;
		this.email = email;
		this.phoneNumber = phoneNumber;
		this.mobileNumber = mobileNumber;
		this.line1 = line1;
		this.line2 = line2;
		this.district = district;
		this.city = city;
		this.state = state;
		this.postalCode = postalCode;
		this.region = region;
		this.latitude = latitude;
		this.longtitude = longtitude;
		this.country = country;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "daId", column = @Column(name = "da_id", nullable = false)),
			@AttributeOverride(name = "payloadId", column = @Column(name = "payload_id", nullable = false, length = 15)),
			@AttributeOverride(name = "adrTypeId", column = @Column(name = "adr_type_id", nullable = false)) })
	public QxmaPlAddressId getId() {
		return this.id;
	}

	public void setId(QxmaPlAddressId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "adr_type_id", nullable = false, insertable = false, updatable = false)
	public QxmaAddressType getQxmaAddressType() {
		return this.qxmaAddressType;
	}

	public void setQxmaAddressType(QxmaAddressType qxmaAddressType) {
		this.qxmaAddressType = qxmaAddressType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "payload_id", nullable = false, insertable = false, updatable = false)
	public QxmaPayload getQxmaPayload() {
		return this.qxmaPayload;
	}

	public void setQxmaPayload(QxmaPayload qxmaPayload) {
		this.qxmaPayload = qxmaPayload;
	}

	@Column(name = "type", length = 10)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "firstname", length = 50)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "lastname", length = 50)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "phone_number", length = 10)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "mobile_number", length = 12)
	public String getMobileNumber() {
		return this.mobileNumber;
	}

	public void setMobileNumber(String mobileNumber) {
		this.mobileNumber = mobileNumber;
	}

	@Column(name = "line1", length = 100)
	public String getLine1() {
		return this.line1;
	}

	public void setLine1(String line1) {
		this.line1 = line1;
	}

	@Column(name = "line2", length = 100)
	public String getLine2() {
		return this.line2;
	}

	public void setLine2(String line2) {
		this.line2 = line2;
	}

	@Column(name = "district", length = 45)
	public String getDistrict() {
		return this.district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

	@Column(name = "city", length = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "state", length = 45)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "postal_code", length = 4)
	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	@Column(name = "region", length = 3)
	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	@Column(name = "latitude", length = 10)
	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	@Column(name = "longtitude", length = 10)
	public String getLongtitude() {
		return this.longtitude;
	}

	public void setLongtitude(String longtitude) {
		this.longtitude = longtitude;
	}

	@Column(name = "country", length = 2)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

}
