package com.osi.finx.model;
// Generated 08 14, 18 5:23:14 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * QxmaFtWalletType generated by hbm2java
 */
@Entity
@Table(name = "qxma_ft_wallet_type", catalog = "finx_db")
public class QxmaFtWalletType implements java.io.Serializable {

	private Long wtId;
	private String code;
	private String description;
	private Set<QxmaFtWallet> qxmaFtWallets = new HashSet<QxmaFtWallet>(0);

	public QxmaFtWalletType() {
	}

	public QxmaFtWalletType(String code, String description, Set<QxmaFtWallet> qxmaFtWallets) {
		this.code = code;
		this.description = description;
		this.qxmaFtWallets = qxmaFtWallets;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "wt_id", unique = true, nullable = false)
	public Long getWtId() {
		return this.wtId;
	}

	public void setWtId(Long wtId) {
		this.wtId = wtId;
	}

	@Column(name = "code", length = 30)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "qxmaFtWalletType")
	public Set<QxmaFtWallet> getQxmaFtWallets() {
		return this.qxmaFtWallets;
	}

	public void setQxmaFtWallets(Set<QxmaFtWallet> qxmaFtWallets) {
		this.qxmaFtWallets = qxmaFtWallets;
	}

}
