package com.osi.finx.model;
// Generated 08 14, 18 5:23:14 PM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * QxmaFtRemittance generated by hbm2java
 */
@Entity
@Table(name = "qxma_ft_remittance", catalog = "finx_db")
public class QxmaFtRemittance implements java.io.Serializable {

	private long id;
	private Long orderId;
	private String referenceId;
	private String bankName;
	private String bankRef;
	private BigDecimal amountDeposited;
	private Long createdBy;
	private Date createdAt;
	private Long updatedBy;
	private Date updatedAt;
	private String remittedBy;
	private Date remittedAt;

	public QxmaFtRemittance() {
	}

	public QxmaFtRemittance(long id) {
		this.id = id;
	}

	public QxmaFtRemittance(long id, Long orderId, String referenceId, String bankName, String bankRef,
			BigDecimal amountDeposited, Long createdBy, Date createdAt, Long updatedBy, Date updatedAt,
			String remittedBy, Date remittedAt) {
		this.id = id;
		this.orderId = orderId;
		this.referenceId = referenceId;
		this.bankName = bankName;
		this.bankRef = bankRef;
		this.amountDeposited = amountDeposited;
		this.createdBy = createdBy;
		this.createdAt = createdAt;
		this.updatedBy = updatedBy;
		this.updatedAt = updatedAt;
		this.remittedBy = remittedBy;
		this.remittedAt = remittedAt;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "order_id")
	public Long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	@Column(name = "reference_id")
	public String getReferenceId() {
		return this.referenceId;
	}

	public void setReferenceId(String referenceId) {
		this.referenceId = referenceId;
	}

	@Column(name = "bank_name")
	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	@Column(name = "bank_ref")
	public String getBankRef() {
		return this.bankRef;
	}

	public void setBankRef(String bankRef) {
		this.bankRef = bankRef;
	}

	@Column(name = "amount_deposited")
	public BigDecimal getAmountDeposited() {
		return this.amountDeposited;
	}

	public void setAmountDeposited(BigDecimal amountDeposited) {
		this.amountDeposited = amountDeposited;
	}

	@Column(name = "created_by")
	public Long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Long createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "updated_by")
	public Long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Long updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "remitted_by")
	public String getRemittedBy() {
		return this.remittedBy;
	}

	public void setRemittedBy(String remittedBy) {
		this.remittedBy = remittedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "remitted_at", length = 19)
	public Date getRemittedAt() {
		return this.remittedAt;
	}

	public void setRemittedAt(Date remittedAt) {
		this.remittedAt = remittedAt;
	}

}
