package com.osi.finx.model;
// Generated 09 7, 18 3:23:59 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * QxmaAppFtShare generated by hbm2java
 */
@Entity
@Table(name = "qxma_app_ft_share", catalog = "finx_db")
public class QxmaAppFtShare implements java.io.Serializable {

	private Integer appFtId;
	private QxmaAppShare qxmaAppShare;
	private QxmaFtProductEvent qxmaFtProductEvent;

	public QxmaAppFtShare() {
	}

	public QxmaAppFtShare(QxmaAppShare qxmaAppShare, QxmaFtProductEvent qxmaFtProductEvent) {
		this.qxmaAppShare = qxmaAppShare;
		this.qxmaFtProductEvent = qxmaFtProductEvent;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "app_ft_id", unique = true, nullable = false)
	public Integer getAppFtId() {
		return this.appFtId;
	}

	public void setAppFtId(Integer appFtId) {
		this.appFtId = appFtId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "app_share_id", nullable = false)
	public QxmaAppShare getQxmaAppShare() {
		return this.qxmaAppShare;
	}

	public void setQxmaAppShare(QxmaAppShare qxmaAppShare) {
		this.qxmaAppShare = qxmaAppShare;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ft_event_prod_id", nullable = false)
	public QxmaFtProductEvent getQxmaFtProductEvent() {
		return this.qxmaFtProductEvent;
	}

	public void setQxmaFtProductEvent(QxmaFtProductEvent qxmaFtProductEvent) {
		this.qxmaFtProductEvent = qxmaFtProductEvent;
	}

}
