package com.osi.finx.model;
// Generated 09 7, 18 3:23:59 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * QxmaOmsEventStatus generated by hbm2java
 */
@Entity
@Table(name = "qxma_oms_event_status", catalog = "finx_db")
public class QxmaOmsEventStatus implements java.io.Serializable {

	private String code;
	private String name;
	private Set<QxmaOmsProductEvent> qxmaOmsProductEvents = new HashSet<QxmaOmsProductEvent>(0);

	public QxmaOmsEventStatus() {
	}

	public QxmaOmsEventStatus(String code, String name) {
		this.code = code;
		this.name = name;
	}

	public QxmaOmsEventStatus(String code, String name, Set<QxmaOmsProductEvent> qxmaOmsProductEvents) {
		this.code = code;
		this.name = name;
		this.qxmaOmsProductEvents = qxmaOmsProductEvents;
	}

	@Id

	@Column(name = "code", unique = true, nullable = false, length = 30)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "qxmaOmsEventStatus")
	public Set<QxmaOmsProductEvent> getQxmaOmsProductEvents() {
		return this.qxmaOmsProductEvents;
	}

	public void setQxmaOmsProductEvents(Set<QxmaOmsProductEvent> qxmaOmsProductEvents) {
		this.qxmaOmsProductEvents = qxmaOmsProductEvents;
	}

}
