package com.osi.finx.model;
// Generated 08 16, 18 6:39:07 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * QxmaFtBankId generated by hbm2java
 */
@Embeddable
public class QxmaFtBankId implements java.io.Serializable {

	private long bankId;
	private int bankAccountTypeBaType;
	private int bankAccountClassBaId;

	public QxmaFtBankId() {
	}

	public QxmaFtBankId(long bankId, int bankAccountTypeBaType, int bankAccountClassBaId) {
		this.bankId = bankId;
		this.bankAccountTypeBaType = bankAccountTypeBaType;
		this.bankAccountClassBaId = bankAccountClassBaId;
	}

	@Column(name = "bank_id", nullable = false)
	public long getBankId() {
		return this.bankId;
	}

	public void setBankId(long bankId) {
		this.bankId = bankId;
	}

	@Column(name = "bank_account_type_ba_type", nullable = false)
	public int getBankAccountTypeBaType() {
		return this.bankAccountTypeBaType;
	}

	public void setBankAccountTypeBaType(int bankAccountTypeBaType) {
		this.bankAccountTypeBaType = bankAccountTypeBaType;
	}

	@Column(name = "bank_account_class_ba_id", nullable = false)
	public int getBankAccountClassBaId() {
		return this.bankAccountClassBaId;
	}

	public void setBankAccountClassBaId(int bankAccountClassBaId) {
		this.bankAccountClassBaId = bankAccountClassBaId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof QxmaFtBankId))
			return false;
		QxmaFtBankId castOther = (QxmaFtBankId) other;

		return (this.getBankId() == castOther.getBankId())
				&& (this.getBankAccountTypeBaType() == castOther.getBankAccountTypeBaType())
				&& (this.getBankAccountClassBaId() == castOther.getBankAccountClassBaId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getBankId();
		result = 37 * result + this.getBankAccountTypeBaType();
		result = 37 * result + this.getBankAccountClassBaId();
		return result;
	}

}
