package com.osi.finx.model;
// Generated 08 14, 18 5:23:14 PM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * QxmaFtTransferType generated by hbm2java
 */
@Entity
@Table(name = "qxma_ft_transfer_type", catalog = "finx_db")
public class QxmaFtTransferType implements java.io.Serializable {

	private Long typeId;
	private String code;
	private String description;
	private Set<QxmaFtTransfer> qxmaFtTransfers = new HashSet<QxmaFtTransfer>(0);

	public QxmaFtTransferType() {
	}

	public QxmaFtTransferType(String code) {
		this.code = code;
	}

	public QxmaFtTransferType(String code, String description, Set<QxmaFtTransfer> qxmaFtTransfers) {
		this.code = code;
		this.description = description;
		this.qxmaFtTransfers = qxmaFtTransfers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "type_id", unique = true, nullable = false)
	public Long getTypeId() {
		return this.typeId;
	}

	public void setTypeId(Long typeId) {
		this.typeId = typeId;
	}

	@Column(name = "code", nullable = false, length = 30)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "qxmaFtTransferType")
	public Set<QxmaFtTransfer> getQxmaFtTransfers() {
		return this.qxmaFtTransfers;
	}

	public void setQxmaFtTransfers(Set<QxmaFtTransfer> qxmaFtTransfers) {
		this.qxmaFtTransfers = qxmaFtTransfers;
	}

}
