package com.osi.finx.model;
// Generated 08 22, 18 4:56:31 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.Embedded;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;


/**
 * RemittanceView generated by hbm2java
 */
@Entity
@Table(name = "remittance_view", catalog = "finx_db")
public class RemittanceView implements java.io.Serializable {

	private RemittanceViewId id;

	public RemittanceView() {
	}

	public RemittanceView(RemittanceViewId id) {
		this.id = id;
	}
	
	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "orderId", column = @Column(name = "order_id")),
			@AttributeOverride(name = "referenceNumber", column = @Column(name = "reference_number")),
			@AttributeOverride(name = "trackingNumber", column = @Column(name = "tracking_number")),
			@AttributeOverride(name = "client", column = @Column(name = "client", nullable = false, length = 6)),
			@AttributeOverride(name = "amount", column = @Column(name = "amount")),
			@AttributeOverride(name = "matchedAmount", column = @Column(name = "matched_amount")),
			@AttributeOverride(name = "varianceAmount", column = @Column(name = "variance_amount")),
			@AttributeOverride(name = "orderStatus", column = @Column(name = "order_status", length = 10)),
			@AttributeOverride(name = "matchStatus", column = @Column(name = "match_status", length = 20)),
			@AttributeOverride(name = "paymentProcessor", column = @Column(name = "payment_processor", nullable = false, length = 17)) })
	public RemittanceViewId getId() {
		return this.id;
	}

	public void setId(RemittanceViewId id) {
		this.id = id;
	}

}
