package com.osi.finx.model;
// Generated 08 22, 18 4:56:31 PM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;

import javax.persistence.Access;
import javax.persistence.AccessType;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RemittanceViewId generated by hbm2java
 */
@Embeddable 
public class RemittanceViewId implements java.io.Serializable {

	private Long orderId;
	private String referenceNumber;
	private String trackingNumber;
	private String client;
	private BigDecimal amount;
	private BigDecimal matchedAmount;
	private BigDecimal varianceAmount;
	private String orderStatus;
	private String matchStatus;
	private String paymentProcessor;

	public RemittanceViewId() {
	}

	public RemittanceViewId(String client, String paymentProcessor) {
		this.client = client;
		this.paymentProcessor = paymentProcessor;
	}

	public RemittanceViewId(Long orderId, String referenceNumber, String trackingNumber, String client,
			BigDecimal amount, BigDecimal matchedAmount, BigDecimal varianceAmount, String orderStatus,
			String matchStatus, String paymentProcessor) {
		this.orderId = orderId;
		this.referenceNumber = referenceNumber;
		this.trackingNumber = trackingNumber;
		this.client = client;
		this.amount = amount;
		this.matchedAmount = matchedAmount;
		this.varianceAmount = varianceAmount;
		this.orderStatus = orderStatus;
		this.matchStatus = matchStatus;
		this.paymentProcessor = paymentProcessor;
	}

	@Column(name = "order_id")
	public Long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	@Column(name = "reference_number")
	public String getReferenceNumber() {
		return this.referenceNumber;
	}

	public void setReferenceNumber(String referenceNumber) {
		this.referenceNumber = referenceNumber;
	}

	@Column(name = "tracking_number")
	public String getTrackingNumber() {
		return this.trackingNumber;
	}

	public void setTrackingNumber(String trackingNumber) {
		this.trackingNumber = trackingNumber;
	}

	@Column(name = "client", nullable = false, length = 6)
	public String getClient() {
		return this.client;
	}

	public void setClient(String client) {
		this.client = client;
	}

	@Column(name = "amount")
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "matched_amount")
	public BigDecimal getMatchedAmount() {
		return this.matchedAmount;
	}

	public void setMatchedAmount(BigDecimal matchedAmount) {
		this.matchedAmount = matchedAmount;
	}

	@Column(name = "variance_amount")
	public BigDecimal getVarianceAmount() {
		return this.varianceAmount;
	}

	public void setVarianceAmount(BigDecimal varianceAmount) {
		this.varianceAmount = varianceAmount;
	}

	@Column(name = "order_status", length = 10)
	public String getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(String orderStatus) {
		this.orderStatus = orderStatus;
	}

	@Column(name = "match_status", length = 20)
	public String getMatchStatus() {
		return this.matchStatus;
	}

	public void setMatchStatus(String matchStatus) {
		this.matchStatus = matchStatus;
	}

	@Column(name = "payment_processor", nullable = false, length = 17)
	public String getPaymentProcessor() {
		return this.paymentProcessor;
	}

	public void setPaymentProcessor(String paymentProcessor) {
		this.paymentProcessor = paymentProcessor;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RemittanceViewId))
			return false;
		RemittanceViewId castOther = (RemittanceViewId) other;

		return ((this.getOrderId() == castOther.getOrderId()) || (this.getOrderId() != null
				&& castOther.getOrderId() != null && this.getOrderId().equals(castOther.getOrderId())))
				&& ((this.getReferenceNumber() == castOther.getReferenceNumber())
						|| (this.getReferenceNumber() != null && castOther.getReferenceNumber() != null
								&& this.getReferenceNumber().equals(castOther.getReferenceNumber())))
				&& ((this.getTrackingNumber() == castOther.getTrackingNumber())
						|| (this.getTrackingNumber() != null && castOther.getTrackingNumber() != null
								&& this.getTrackingNumber().equals(castOther.getTrackingNumber())))
				&& ((this.getClient() == castOther.getClient()) || (this.getClient() != null
						&& castOther.getClient() != null && this.getClient().equals(castOther.getClient())))
				&& ((this.getAmount() == castOther.getAmount()) || (this.getAmount() != null
						&& castOther.getAmount() != null && this.getAmount().equals(castOther.getAmount())))
				&& ((this.getMatchedAmount() == castOther.getMatchedAmount())
						|| (this.getMatchedAmount() != null && castOther.getMatchedAmount() != null
								&& this.getMatchedAmount().equals(castOther.getMatchedAmount())))
				&& ((this.getVarianceAmount() == castOther.getVarianceAmount())
						|| (this.getVarianceAmount() != null && castOther.getVarianceAmount() != null
								&& this.getVarianceAmount().equals(castOther.getVarianceAmount())))
				&& ((this.getOrderStatus() == castOther.getOrderStatus())
						|| (this.getOrderStatus() != null && castOther.getOrderStatus() != null
								&& this.getOrderStatus().equals(castOther.getOrderStatus())))
				&& ((this.getMatchStatus() == castOther.getMatchStatus())
						|| (this.getMatchStatus() != null && castOther.getMatchStatus() != null
								&& this.getMatchStatus().equals(castOther.getMatchStatus())))
				&& ((this.getPaymentProcessor() == castOther.getPaymentProcessor())
						|| (this.getPaymentProcessor() != null && castOther.getPaymentProcessor() != null
								&& this.getPaymentProcessor().equals(castOther.getPaymentProcessor())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getOrderId() == null ? 0 : this.getOrderId().hashCode());
		result = 37 * result + (getReferenceNumber() == null ? 0 : this.getReferenceNumber().hashCode());
		result = 37 * result + (getTrackingNumber() == null ? 0 : this.getTrackingNumber().hashCode());
		result = 37 * result + (getClient() == null ? 0 : this.getClient().hashCode());
		result = 37 * result + (getAmount() == null ? 0 : this.getAmount().hashCode());
		result = 37 * result + (getMatchedAmount() == null ? 0 : this.getMatchedAmount().hashCode());
		result = 37 * result + (getVarianceAmount() == null ? 0 : this.getVarianceAmount().hashCode());
		result = 37 * result + (getOrderStatus() == null ? 0 : this.getOrderStatus().hashCode());
		result = 37 * result + (getMatchStatus() == null ? 0 : this.getMatchStatus().hashCode());
		result = 37 * result + (getPaymentProcessor() == null ? 0 : this.getPaymentProcessor().hashCode());
		return result;
	}

}
